Make builtins a hybrid type (symbol & data)
software-mansion/TypeGPU pull request #386
Opened 2024-09-24 13:34 UTC by mhawryluk

closes #371

2024-09-24 20:02 UTC, iwoplaza requested changes

2024-09-24 20:02 UTC, iwoplaza commented on packages/typegpu/src/builtin.ts
> +export type BuiltinNumWorkgroups = symbol & vec3u;
The builtins should be the value type, not the schema type, so they can be used as if they were just normal values in from TypeScript's point of view.

```suggestion
export type BuiltinVertexIndex = symbol & number;
export type BuiltinInstanceIndex = symbol & number;
export type BuiltinPosition = symbol & vec4f;
export type BuiltinClipDistances = symbol & number[];
export type BuiltinFrontFacing = symbol & boolean;
export type BuiltinFragDepth = symbol & number;
export type BuiltinSampleIndex = symbol & number;
export type BuiltinSampleMask = symbol & vec4f;
export type BuiltinFragment = symbol & vec4f;
export type BuiltinLocalInvocationId = symbol & vec3u;
export type BuiltinLocalInvocationIndex = symbol & number;
export type BuiltinGlobalInvocationId = symbol & vec3u;
export type BuiltinWorkgroupId = symbol & vec3u;
export type BuiltinNumWorkgroups = symbol & vec3u;
```

2024-09-24 20:02 UTC, iwoplaza commented on packages/typegpu/tests/builtin.test.ts
> +    });
The generic parameter can be used to test a specific type, not the type of a value.
```suggestion
    expectTypeOf<Omitted>().toEqualTypeOf({
      a: u32,
      c: f32,
    });
```

2024-09-25 08:18 UTC, mhawryluk commented
apparently `symbol & <some primitive type>` is `never`. i'm afraid that's a big issue for us here

<img width="470" alt="Zrzut ekranu 2024-09-25 o 10 14 42" src="https://github.com/user-attachments/assets/3e078755-ca8e-4c75-8acb-60af16d08b4d">

2024-09-25 09:12 UTC, iwoplaza commented
> apparently `symbol & <some primitive type>` is `never`. i'm afraid that's a big issue for us here
> 
> <img alt="Zrzut ekranu 2024-09-25 o 10 14 42" width="470" src="https://private-user-images.githubusercontent.com/70582973/370626713-3e078755-ca8e-4c75-8acb-60af16d08b4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTU2ODksIm5iZiI6MTcyNzI1NTM4OSwicGF0aCI6Ii83MDU4Mjk3My8zNzA2MjY3MTMtM2UwNzg3NTUtY2E4ZS00Yzc1LThhY2ItNjBhZjE2ZDA4YjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA5MDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNmIyN2I2YmE2YmY1YjVkODg0MTU4MGZlYWNkMmUyYWQzYzY3ZDczMWI5NDY2ZmUzZjZmNjM2YWNlOWM5NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.auGPDHZbwemyUgnNkzjEnPsVsPsAUXBFFINWMNZifvE">

It is an issue, hmm. We could go about it a few different ways. The current use of Vertex and Fragment output structs makes it so we are not using builtins as keys, so they do not really have to be symbols anymore. We can make a Builtin class that has a parameter we can check at runtime, and then do `Builtin & number`, which should work fine.

2024-10-02 16:43 UTC, iwoplaza approved these changes
Beautiful 🥹

2024-10-03 07:09 UTC, merged