Docs on `wgpu-matrix` integration
software-mansion/TypeGPU pull request #503
Opened 2024-10-28 16:07 UTC by reczkok

closes #499

2024-10-29 13:06 UTC, iwoplaza commented on apps/typegpu-docs/astro.config.mjs
Could we move it into a new "Integration" section, and rename it to "Working with wgpu-matrix"?

![image](https://github.com/user-attachments/assets/95668992-d26c-4d80-b75b-fc9486ff234f)

2024-10-29 14:14 UTC, iwoplaza requested changes

2024-10-29 14:14 UTC, iwoplaza commented on apps/typegpu-docs/src/content/docs/guides/wgpu-matrix-integration.mdx
> +The [wgpu-matrix](https://github.com/greggman/wgpu-matrix) library is a popular tool for WebGPU developers to work with matrices.
Tiny suggestion.
```suggestion
The [wgpu-matrix](https://github.com/greggman/wgpu-matrix) library provides utilities for matrix and vector math, which is essential for graphics programming.
```

2024-10-29 14:14 UTC, iwoplaza commented on apps/typegpu-docs/src/content/docs/guides/wgpu-matrix-integration.mdx
> +It is designed from the ground up to be compatible with WebGPU, and it provides a lot of useful features.
```suggestion
It is designed from the ground up to be compatible with WebGPU, and TypeGPU works with it seamlessly.
```

2024-10-29 14:14 UTC, iwoplaza commented on apps/typegpu-docs/src/content/docs/guides/wgpu-matrix-integration.mdx
> +From `wgpu-matrix` version `3.3.0` and `typegpu` version `0.2.0`, it is possible to use TypeGPU primitives inside the `wgpu-matrix` library.
Suggestion, could we make this a note?

```suggestion
:::note[Supported versions]
`wgpu-matrix`: 3.3.0 and up
`typegpu`: 0.2.0 and up
:::
```

2024-10-29 14:14 UTC, iwoplaza commented on apps/typegpu-docs/src/content/docs/guides/wgpu-matrix-integration.mdx
> +For example, you can create a vector and normalize it like this:
Imo, we can skip the technical details of how it works.

```suggestion
You can create a vector and normalize it like this:
```

2024-10-30 11:15 UTC, mhawryluk approved these changes
Cool 🆒

2024-10-30 11:19 UTC, iwoplaza approved these changes
AMAZING

2024-10-30 11:19 UTC, merged