Update fluid with atomics example
software-mansion/TypeGPU pull request #671
Opened 2024-12-18 13:16 UTC by reczkok

closes #657

2025-01-08 12:55 UTC, mhawryluk commented
```
packages/typegpu dev:watch: Export "AnyWgslData" of module "src/data/wgslTypes.ts" was reexported through module "src/data/index.ts" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
packages/typegpu dev:watch: Either change the import in "src/core/slot/accessor.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
packages/typegpu dev:watch: Export "AnyWgslData" of module "src/data/wgslTypes.ts" was reexported through module "src/data/index.ts" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
packages/typegpu dev:watch: Either change the import in "src/core/slot/slotTypes.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
packages/typegpu dev:watch: Export "AnyData" of module "src/data/dataTypes.ts" was reexported through module "src/data/index.ts" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
packages/typegpu dev:watch: Either change the import in "src/tgpuBindGroupLayout.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
```

⚠️

2025-01-16 10:54 UTC, mhawryluk requested changes
- remember to merge the main branch, because experimental is no more
- brush size value is effectively shifted by 1 (setting 0 draws 1 square)
- it is very difficult to draw anything with timestep set to low values (don't know if we can do anything about this, maybe rearranging the order of operations could help somehow?)

2025-01-16 10:54 UTC, mhawryluk commented on apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics/index.ts
> +}`)
```suggestion
const getCell = tgpu
  .fn([d.u32, d.u32], d.u32)
  .does(/* wgsl */ `(x: u32, y: u32) -> u32 {
    return currentStateData[getIndex(x, y)];
  }`)
```

same for all the other functions above and below

2025-01-16 10:54 UTC, mhawryluk commented on apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics/index.ts
> +  let waterLevel = cell & ${MAX_WATER_LEVEL};
we can put `MAX_WATER_LEVEL` in `$uses` instead of using string interpolation and I'd go with that instead to make it more unified, but I don't insist. same everywhere else

2025-01-16 10:54 UTC, mhawryluk commented on apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics/index.ts
> +  } else if (totalMass >= ${MAX_WATER_LEVEL_UNPRESSURIZED}*2 && upper > lower) {
```suggestion
  } else if (totalMass >= ${MAX_WATER_LEVEL_UNPRESSURIZED} * 2 && upper > lower) {
```

2025-01-16 10:54 UTC, mhawryluk commented on apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics/index.ts
> +  const cpp = root.withCompute(compute).createPipeline();
`cpp` -> `computePipeline`

2025-01-16 10:54 UTC, mhawryluk commented on apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics/index.ts
> +  const vp = root
`vp` -> `renderPipeline`

2025-01-16 10:54 UTC, mhawryluk commented on apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics/index.ts
> +    return vec4f(0.937, 0.937, 0.976, 1.);
```suggestion
    return vec4f();
```

2025-01-25 14:14 UTC, iwoplaza commented on packages/typegpu/src/data/attributes.ts
> +    : Decorated<TInner, TAttribs>;
I am not 100% sure, but wouldn't the MemIdentity of a Decorated type be this instead?:
```suggestion
  public readonly '~memIdent'!: TAttribs extends Location<number>[]
    ? MemIdentity<TInner> | Decorated<MemIdentity<TInner>, TAttribs>
    : Decorated<MemIdentity<TInner>, TAttribs>;
```

2025-02-06 15:19 UTC, iwoplaza commented on apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics/index.ts
> +  const allAffectedCells = new Set<{ x: number; y: number }>();
Turn back into array as the Set does not guarantee uniqueness in this case 🙏

2025-02-06 15:22 UTC, iwoplaza approved these changes
A W E S O M E

2025-02-06 17:29 UTC, reczkok commented on apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics/index.ts
> +  const allAffectedCells = new Set<{ x: number; y: number }>();
It actually needed neither 🫡

2025-02-06 17:44 UTC, merged